### ISSUE TITLE
Institute home page has front-end issues

### ISSUE THREAD

**Issue by DarKnight--** [no-Or/Website#13]
The home page of institute have the following problem as shown in screenshot.
![screenshot from 2015-07-08 12 26 58](https://cloud.githubusercontent.com/assets/6971456/8564762/d18972d2-256c-11e5-8121-c9218e211e98.png)

The mobile view should hide the image section and should only have alerts and other informations. The current front-end of the institute home page requires a complete review for extra small screen sizes.

**Comment by no-Or** [comment]
fixed it!!
